import pathlib, re
p=pathlib.Path(r'D:\KITTY\src\pet_window.py')
txt=p.read_text(encoding='utf-8')
msgs=[
"You got this - Madhu believes in you!",
"One line at a time, you are building something beautiful",
"Take a breath, you have solved harder problems before",
"Go make that model shine - I am right here watching",
"Architecture is patience - your lines will find their place",
"Blueprint by blueprint, you are closer",
"Trust your eye, it has gotten you this far",
"Small details make great buildings - keep going",
"Every great model started with a sketch - keep sketching",
"Your persistence is the strongest foundation",
"The best designs take time - yours is coming together",
"You have the vision - now let it unfold",
"One more wall and the space comes alive",
"Your creativity is your superpower today",
"Breathe, adjust that scale, you have got this",
"The site will thank you for this care",
"You are not stuck, you are refining",
"That section will click any second now",
"Keep the pencil moving - magic happens there",
"Your hard work is already showing",
"You make complex feel simple - keep it up",
"The rendering will be worth the wait",
"Light, shadow, you understand it - trust it",
"Your studio hours are paying off",
"This is not a block, it is a pause before clarity",
"You have solved tougher sections before",
"The model is lucky to have you",
"Keep going, Madhu is purring for you",
"You are building more than a model - you are building skill",
"The next line could be the one",
"Your dedication is beautiful to watch",
"You are exactly where you need to be",
"Take a sip, stretch, then nail that detail",
"The plan is coming together, keep it up",
"Your eye for proportion is spot on",
"You handle pressure like a pro",
"That facade is going to be stunning",
"Your ideas deserve to be built - keep building",
"The hard part is almost behind you",
"You are turning stress into structure",
"Keep that scale handy - you have got precision",
"The journey is the design - enjoy this part",
"Your focus is your strength today",
"You are making your future self proud",
"One more extrude and you will see it",
"The client will love what you are making",
"Your lines have intent - trust them",
"You are crafting space, not just drawings",
"The sun study will be perfect - keep tweaking",
"Your model has good bones - keep fleshing it",
"You are closer than you think",
"That courtyard will feel amazing",
"Your patience is architectural",
"You are doing amazing, keep the momentum",
"The details you add matter",
"Your vision is clear - follow it",
"Take it one floor at a time",
"You are learning with every line",
"The building is taking shape because of you",
"Your effort today is tomorrow s portfolio",
"You have got the eye - now trust the hand",
"The massing is strong - refine it",
"Your ideas are worth the effort",
"Keep that trace paper rolling",
"You are not behind, you are building",
"The section is speaking - listen",
"Your work ethic is inspiring",
"You make the studio brighter",
"That texture will pop - keep it",
"You are in flow, stay there",
"The next save will feel great",
"Your draft is already better than yesterday",
"You are allowed to take a break - keep going",
"The light you design will guide someone",
"Your precision will pay off",
"You are the architect of your own success",
"Keep that cursor moving - you have got this",
"The hardest line is the first - you did it",
"Your model is breathing - keep it alive",
"You are making progress, even if slow",
"The plan needs your touch - give it",
"Your style is emerging - trust it",
"You are handling this like a designer",
"The elevation will be worth it",
"Your hands know what to do",
"The site deserves your vision",
"You are building confidence with every click",
"That stair will be elegant - keep refining",
"Your concept is strong - detail it",
"You are not alone - Madhu is here",
"The render is almost ready - patience",
"Your lines are confident today",
"Keep that passion lit",
"The building will stand because you stood by it",
"You are making your professors proud",
"Your future office will thank you",
"The next undo is not needed - trust it",
"You are designing with heart",
"The mass will balance - you will see",
"Your work is valid and valuable",
"Take a breath, the deadline will bend",
"You are more prepared than you feel",
"The model is your story - tell it",
"Your skill is growing with every hour",
"That roof will be iconic",
"You are pushing through - respect that",
"The drawing deserves your care - give it",
"You are exactly the architect for this job",
"The viewport is your playground - play",
"Your ideas are not too big - build them",
"You are making the complex clear",
"The next layer will bring it together",
"Your draft is your power",
"You are not stuck - you are thinking",
"The building is lucky to be yours",
"You are doing the work - that is winning",
"Keep that lineweight consistent - you have got it",
"The studio believes in you",
"Your vision will become shelter",
"You are shaping space and future",
"That corner detail will be loved",
"You are allowed to be proud now",
"The plan is patient - be patient with it",
"Your hands are steady - trust them",
"You are making it happen",
"The design will thank you later",
"Your focus is your magic",
"You are not lost - you are exploring",
"The model will render beautifully",
"Your effort is the blueprint for success",
"You are building at your own perfect pace",
"That material choice is chef kiss",
"Your persistence will be remembered",
"The building is becoming real because of you",
"You are doing enough and you are enough",
"Keep that layer on - you need it",
"Your eye will catch the right proportion",
"You are the reason this project moves",
"The next orbit will show you the answer",
"Your design has heart - keep it",
"You are making your mark",
"The toughest part is the thinking - you did",
"Your lines are your language",
"You are designing courage",
"The site is waiting for your idea",
"Your work matters - keep sharing it",
"You are not behind - you are thorough",
"The rendering will sing - keep composing",
"Your model is your meditation",
"You are building resilience too",
"The next line will feel right",
"Your creativity is not blocked - it is brewing",
]
msgs=msgs[:150]
new_block='    LUCK_MESSAGES = [\n' + '\n'.join(f'        "{m}",' for m in msgs) + '\n    ]'
txt=re.sub(r'    LUCK_MESSAGES = \[.*?\]', new_block, txt, flags=re.DOTALL)
p.write_text(txt, encoding='utf-8')
print('wrote', len(msgs), 'messages')
